Feature/create infrastructure
RuprechtKraus/Cookbook_v2 pull request #4
Opened 2022-08-20 14:05 UTC by RuprechtKraus

2022-08-24 19:25 UTC, ReactiveTurtle requested changes

2022-08-24 19:25 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/FavoriteRecipe.cs
> +        protected FavoriteRecipe()
Почему protected?

2022-08-24 19:25 UTC, ReactiveTurtle commented on Cookbook_v2.Infrastructure/Data/RecipeModel/Configurations/RecipeStepConfiguration.cs
> +            builder.ToTable( "RecipeStep" );
Зачем это?

2022-08-24 20:57 UTC, RuprechtKraus commented on Cookbook_v2.Domain/RecipeModel/FavoriteRecipe.cs
> +        protected FavoriteRecipe()
Сделал защищенный как у тебя, ибо для EFCore же надо

2022-08-24 20:59 UTC, RuprechtKraus commented on Cookbook_v2.Infrastructure/Data/RecipeModel/Configurations/RecipeStepConfiguration.cs
> +            builder.ToTable( "RecipeStep" );
По умолчанию он таблицы во множественном числе именует. Было бы RecipeSteps. А как отключить эту функцию в EF Core я не нашел. В EF6 было что-то такое

2022-08-26 07:13 UTC, ReactiveTurtle requested changes

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Api/Startup.cs
> +                );
Скобка ушла куда-то не туда
Убери 1 таб или же перенеси на строку 54

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/RecipeIngredientsSection.cs
> +        protected RecipeIngredientsSection()
Добавь коммент Workaround for EF, чтобы не возникало вопросов для чего такой конструктор

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/RecipeLike.cs
> +        protected RecipeLike()
Комментарий для EF

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/RecipeStep.cs
> +        protected RecipeStep()
Коммент

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/RecipeStep.cs
>          public int RecipeId { get; set; }
Давай добавим отступ выше для разделения статических полей и полей класса

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/UserModel/IUserRepository.cs
> +        Task RemoveFavoriteRecipe( FavoriteRecipe favRecipe );
Пиши полное название переменной

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/UserModel/User.cs
> +        protected User()
Коммент

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/RecipeModel/RecipeIngredientsSection.cs
> +        public static readonly int s_titleMaxLength = 50;
Давай не будем использовать префикс для публичных статических полей
Пишем в стиле PascalCase такие вещи

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Infrastructure/Data/RecipeModel/RecipeRepository.cs
> +            Recipe recipe = await _context.Recipes.SingleOrDefaultAsync( x => x.Id == id );
Достать нужно снаружи, не надо в репозитории проверять наличие рецепта, пусть это делает Api

2022-08-26 07:13 UTC, ReactiveTurtle commented on Cookbook_v2.Infrastructure/Data/RecipeModel/Configurations/RecipeConfiguration.cs
> +            builder.HasIndex( x => x.Title );
Ты где-то достаёшь рецепт по его заголовку?
Вроде нет, значит и индекс не нужен

2022-08-30 16:38 UTC, merged