feat/контроллер пользователя и изменена структура проекта
RuprechtKraus/Cookbook_v2 pull request #5
Opened 2022-08-27 17:37 UTC by RuprechtKraus

Добавлена возможность регистрации и аутентификации пользователей и полностью переработана структура проекта

2022-08-29 07:56 UTC, ReactiveTurtle requested changes

2022-08-29 07:56 UTC, ReactiveTurtle commented on Cookbook_v2.Application/Converters/UserConverter.cs
> +    public static class UserConverter
Зачем нам пустой конвертер?

2022-08-29 11:44 UTC, RuprechtKraus commented on Cookbook_v2.Application/Converters/UserConverter.cs
> +    public static class UserConverter
Создал да забыл пока за ненадобностью. На будущее будет для загрузки пользователей

2022-08-30 07:52 UTC, ReactiveTurtle commented
Поменяй название PR
Там не слеш, а двоеточие

2022-08-30 07:57 UTC, ReactiveTurtle commented on Cookbook_v2.Domain/Entities/UserModel/User.cs
> +        [JsonIgnore]
Это с чего вдруг тут Json?

2022-08-30 15:48 UTC, RuprechtKraus commented on Cookbook_v2.Domain/Entities/UserModel/User.cs
> +        [JsonIgnore]
Убрал

2022-08-30 16:02 UTC, ReactiveTurtle approved these changes

2022-08-30 16:38 UTC, merged